//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresta.Aplicacao.MensagemErros {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empresta.Aplicacao.MensagemErros.MensagensErro", typeof(MensagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro é obrigatório..
        /// </summary>
        public static string BairroEObrigatorio {
            get {
                return ResourceManager.GetString("BairroEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cep é obrigatório.
        /// </summary>
        public static string CepEObrigatorio {
            get {
                return ResourceManager.GetString("CepEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade é obrigatório..
        /// </summary>
        public static string CidadeEObrigatorio {
            get {
                return ResourceManager.GetString("CidadeEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente já foi cadastrado para esse funcionário..
        /// </summary>
        public static string ClienteJaCadastradoParaEsseFuncionario {
            get {
                return ResourceManager.GetString("ClienteJaCadastradoParaEsseFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dd está inválido.
        /// </summary>
        public static string DdInvalido {
            get {
                return ResourceManager.GetString("DdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tente mais tarde, o servidor está indisponivel.
        /// </summary>
        public static string ErroSistematico {
            get {
                return ResourceManager.GetString("ErroSistematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado é obrigatório..
        /// </summary>
        public static string EstadoEObrigatorio {
            get {
                return ResourceManager.GetString("EstadoEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O funcionário id é obrigatório..
        /// </summary>
        public static string FuncionarioIdEObrigatorio {
            get {
                return ResourceManager.GetString("FuncionarioIdEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um caixa em aberto, fecha ele antes para abri um novo..
        /// </summary>
        public static string JaExisteCaixaAberto {
            get {
                return ResourceManager.GetString("JaExisteCaixaAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado o funcionário  de Id: {0}.
        /// </summary>
        public static string NaoEncontradoOFuncionario {
            get {
                return ResourceManager.GetString("NaoEncontradoOFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeEObrigatorio {
            get {
                return ResourceManager.GetString("NomeEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero é obrigatório..
        /// </summary>
        public static string NumeroEObrigatorio {
            get {
                return ResourceManager.GetString("NumeroEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do telefone está inválido..
        /// </summary>
        public static string NumeroTelefoneInvalido {
            get {
                return ResourceManager.GetString("NumeroTelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O rua é obrigatório.
        /// </summary>
        public static string RuaEObrigatorio {
            get {
                return ResourceManager.GetString("RuaEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor inicial é obrigatório.
        /// </summary>
        public static string ValorInicialEObrigatorio {
            get {
                return ResourceManager.GetString("ValorInicialEObrigatorio", resourceCulture);
            }
        }
    }
}
